[tools]
age = "latest"
bun = "latest"
go = "latest"
node = "latest"
pipx = "latest"
python = "latest"
rust = "latest"
sops = "latest"
uv = "latest"
watchexec = "latest"
usage = "latest"

neovim = "latest"

"cargo:git-absorb" = "latest"
"cargo:mergiraf" = "latest"
"cargo:shpool" = { version = "latest", os = ["linux"]}
"github:atanunq/viu" = "latest"
"github:crate-ci/typos" = "latest"
"github:eza-community/eza" = "latest"
"github:lusingander/serie" = "latest"
"github:skim-rs/skim" = "latest"
"github:starship/starship" = "latest"
"github:tree-sitter/tree-sitter" = "latest"
bat = "latest"
difftastic = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
poetry = "latest"
ripgrep = "latest"
shellcheck = "latest"
tmux = "latest"
zellij = "latest"
zoxide = "latest"

# LSP
"npm:bash-language-server" = "latest"
"github:tekumara/typos-lsp" = "latest"
"pipx:basedpyright" = "latest"
"pipx:magika" = "latest"
lua-language-server = "latest"
